name: CI/CD for Microservices

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      PORT: ${{ secrets.PORT }}
      PORT2: ${{ secrets.PORT2 }} #port2 is for inventory service
      MONGO_URL: ${{ secrets.MONGO_URL }}
      DEV_MODE: ${{ secrets.DEV_MODE }}
      AWS_REGION: ${{ secrets.AWS_REGION }} # Make sure you store AWS region in GitHub secrets
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} # Your AWS access key
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # Your AWS secret key
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      EMAIL_USER: ${{ secrets.EMAIL_USER }}
      EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
      FRONTEND_URL: ${{ secrets.FRONTEND_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # ---------- SNYK: Scan user-service ----------
      - name: Snyk scan for user-service
        run: |
          npm install -g snyk
          cd user-service
          snyk test --severity-threshold=high || true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # ---------- SNYK: Scan inventory-service ----------
      - name: Snyk scan for inventory-service
        run: |
          npm install -g snyk
          cd inventory-service
          snyk test --severity-threshold=high || true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # ---------- SONARCLOUD: Scan user-service ----------
      - name: SonarCloud scan for user-service
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: user-service
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_PROJECT_KEY: IT21228612_CTSE_Assignmant_Y4S2_Microservices
          SONAR_ORGANIZATION: jeewantha-de-silva

      # ---------- SONARCLOUD: Scan inventory-service ----------
      - name: SonarCloud scan for inventory-service
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: inventory-service
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_PROJECT_KEY: IT21228612_CTSE_Assignmant_Y4S2_Microservices
          SONAR_ORGANIZATION: jeewantha-de-silva

      # ---------- Authenticate to AWS ECR ----------
      - name: Authenticate to AWS ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 730615659624.dkr.ecr.$AWS_REGION.amazonaws.com
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # ---------- Build and Push user-service to ECR ----------
      - name: Build user-service Docker image
        run: |
          docker build \
            --build-arg PORT=$PORT \
            --build-arg MONGO_URL=$MONGO_URL \
            --build-arg DEV_MODE=$DEV_MODE \
            --build-arg JWT_SECRET=$JWT_SECRET \
            --build-arg EMAIL_USER=$EMAIL_USER \
            --build-arg EMAIL_PASS=$EMAIL_PASS \
            --build-arg FRONTEND_URL=$FRONTEND_URL \
            -t 730615659624.dkr.ecr.$AWS_REGION.amazonaws.com/ctse/user-service:latest ./user-service

      - name: Push user-service image to ECR
        run: |
          docker push 730615659624.dkr.ecr.$AWS_REGION.amazonaws.com/ctse/user-service:latest

      # ---------- Build and Push inventory-service to ECR ----------
      - name: Build inventory-service Docker image
        run: |
          docker build \
            --build-arg PORT=$PORT2 \
            --build-arg MONGO_URL=$MONGO_URL \
            --build-arg DEV_MODE=$DEV_MODE \
            -t 730615659624.dkr.ecr.$AWS_REGION.amazonaws.com/ctse/inventory-service:latest ./inventory-service

      - name: Push inventory-service image to ECR
        run: |
          docker push 730615659624.dkr.ecr.$AWS_REGION.amazonaws.com/ctse/inventory-service:latest
